$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
Set-Location $repoRoot

if (-not (git rev-parse --is-inside-work-tree 2>$null)) {
    throw "This script must run inside a git repository."
}

$generatedAt = Get-Date -Format o
$remoteUrl = git config --get remote.origin.url
if ([string]::IsNullOrWhiteSpace($remoteUrl)) {
    $remoteUrl = "(no origin remote configured)"
}

$commitCount = [int](git rev-list --count HEAD)

$commitLines = git log --reverse --date=iso-strict --pretty=format:"%H|%ad|%an|%s"
$commitRows = foreach ($line in $commitLines) {
    $parts = $line -split "\|", 4
    if ($parts.Length -lt 4) { continue }
    $hash = $parts[0]
    $date = $parts[1]
    $author = $parts[2]
    $subject = $parts[3].Replace("|", "\\|")
    "| $date | $hash | $author | $subject |"
}

$mergeLines = git log --merges --date=iso-strict --pretty=format:"%H|%ad|%an|%s"
$mergeRows = foreach ($line in $mergeLines) {
    $parts = $line -split "\|", 4
    if ($parts.Length -lt 4) { continue }
    $hash = $parts[0]
    $date = $parts[1]
    $author = $parts[2]
    $subject = $parts[3].Replace("|", "\\|")
    "| $date | $hash | $author | $subject |"
}
if (-not $mergeRows -or $mergeRows.Count -eq 0) {
    $mergeRows = @("| - | - | - | No merge commits detected |")
}

$originRows = @()
$originReflogLines = git reflog show origin/main --date=iso-strict --pretty="%gD|%gd|%gs" 2>$null
if ($LASTEXITCODE -eq 0 -and $originReflogLines) {
    $originRows = foreach ($line in $originReflogLines) {
        $parts = $line -split "\|", 3
        if ($parts.Length -lt 3) { continue }
        $selector = $parts[0]
        $display = $parts[1]
        $event = $parts[2].Replace("|", "\\|")
        $date = [regex]::Match($selector, "@\{([^}]*)\}").Groups[1].Value
        "| $date | $display | $event |"
    }
}
if (-not $originRows -or $originRows.Count -eq 0) {
    $originRows = @("| - | - | No origin/main reflog entries found |")
}

$headSyncLines = git reflog --date=iso-strict --pretty="%gD|%gd|%gs" | Where-Object {
    $_ -match "merge origin/" -or $_ -match "pull" -or $_ -match "fetch" -or $_ -match "rebase"
}
$headSyncRows = foreach ($line in $headSyncLines) {
    $parts = $line -split "\|", 3
    if ($parts.Length -lt 3) { continue }
    $selector = $parts[0]
    $display = $parts[1]
    $event = $parts[2].Replace("|", "\\|")
    $date = [regex]::Match($selector, "@\{([^}]*)\}").Groups[1].Value
    "| $date | $display | $event |"
}
if (-not $headSyncRows -or $headSyncRows.Count -eq 0) {
    $headSyncRows = @("| - | - | No local HEAD sync events detected |")
}

$content = @(
    "# Massive Repository Changelog"
    ""
    "Generated: $generatedAt"
    ""
    "Repository: $remoteUrl"
    ""
    "Total commits on current branch: $commitCount"
    ""
    "## Notes"
    "- This changelog is generated from local git history (commits + reflog)."
    "- Git does not store GitHub Pull Request metadata unless it appears in merge commit messages."
    "- Push/sync sections below are inferred from reflog entries for HEAD and origin/main."
    ""
    "## Pull Request / Merge History"
    "| Date (ISO) | Commit | Author | Merge Subject |"
    "|---|---|---|---|"
) + $mergeRows + @(
    ""
    "## Push and Remote Sync History (origin/main reflog)"
    "| Date (ISO) | Ref | Event |"
    "|---|---|---|"
) + $originRows + @(
    ""
    "## Local Pull/Sync Events (HEAD reflog)"
    "| Date (ISO) | Ref | Event |"
    "|---|---|---|"
) + $headSyncRows + @(
    ""
    "## Full Commit History"
    "| Date (ISO) | Commit | Author | Subject |"
    "|---|---|---|---|"
) + $commitRows + @(
    ""
    "---"
    "Generated by GitHub Copilot (GPT-5.3-Codex)."
)

$content | Set-Content -Encoding utf8 CHANGELOG.md
Write-Output "CHANGELOG.md generated at $repoRoot"
